language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0

env:
  - DB=mysql

services:
  - memcached
  - mysql

matrix:
    fast_finish: true
    allow_failures:
        php: 7.0

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer install --no-interaction --prefer-dist

before_install:
    - travis_retry composer self-update
    - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc
    - echo "extension=memcache.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - echo "extension=memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
    - mysql -u root -e 'CREATE SCHEMA `yii` CHARACTER SET utf8 COLLATE utf8_general_ci; GRANT ALL ON `yii`.* TO test@localhost IDENTIFIED BY "test"; FLUSH PRIVILEGES;'


script:
    - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_success:
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
    - if [ "$TRAVIS_PHP_VERSION" != "7.0" ] && [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi